                                     																																	
/*=============================================================================================================================*/																														
/*=============================================| CRIANDO BANCO DE DADOS - FUT |=============================================*/

USE master;
GO


DROP DATABASE IF EXISTS eFUT;


CREATE DATABASE eFUT;
GO


USE eFUT
GO

/*------------------------------------------------|Criando grupos de arquivos|------------------------------------------------*/

ALTER DATABASE eFUT ADD FILEGROUP FG_eFUT;

ALTER DATABASE eFUT
ADD FILE 
(

	NAME = N'eFUT_X', 
	FILENAME = N'C:\SQL_DATA\eFUT_X.ndf',
	SIZE = 10MB, 
	MAXSIZE = 500MB, 
	FILEGROWTH = 10MB
) 
TO FILEGROUP FG_eFut;

/*========================================================| MODULO SISTEMA DE ORGANIZAÇÃO DE FUT'S - INICIO |========================================================*/

CREATE  TABLE dbo.Log_Erros (
    ID INT IDENTITY PRIMARY KEY,
    DataErro DATETIME DEFAULT GETDATE(),
    NumeroErro INT,
    MensagemErro NVARCHAR(4000),
    LinhaErro INT,
    NomeProcedure NVARCHAR(128)
);


CREATE TABLE dbo.LOCAIS_JOGOS (
    ID_LOCAL INT IDENTITY,
    NOME VARCHAR(100) NOT NULL,
    CEP VARCHAR(10),
    RUA VARCHAR(100),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(50),
    LOCALIZACAO VARCHAR(200),
    VALOR_HORA MONEY,
    TIPO_PAG VARCHAR(50),
	CONSTRAINT PK_LOCAIS_JOGOS PRIMARY KEY CLUSTERED (ID_LOCAL ASC)
		WITH (
        PAD_INDEX = OFF,
        STATISTICS_NORECOMPUTE = OFF,
        IGNORE_DUP_KEY = OFF,
        ALLOW_ROW_LOCKS = ON,
        ALLOW_PAGE_LOCKS = ON,
        FILLFACTOR = 90
    ) ON FG_eFut,
	CONSTRAINT CK_LOCAIS_JOGOS_TIPO_PAG CHECK (TIPO_PAG IN ('MENSALISTA', 'INDIVIDUAL'))
)ON FG_eFut;

CREATE TABLE dbo.JOGOS (
    ID_JOGO INT IDENTITY,
    DATA DATE NOT NULL,
    HR_INI TIME NOT NULL,
    HR_FIM TIME NOT NULL,
    ID_LOCAL INT NOT NULL,
    ID_PREMIACAO INT,
    VAGAS_LINHAS INT NOT NULL DEFAULT 16,
    VAGAS_GOL INT NOT NULL DEFAULT 3,
    VAGAS_SUPLENTES INT NOT NULL DEFAULT 4,
    CONSTRAINT PK_JOGO PRIMARY KEY CLUSTERED (ID_JOGO ASC)
        WITH (
            PAD_INDEX = OFF,
            STATISTICS_NORECOMPUTE = OFF,
            IGNORE_DUP_KEY = OFF,
            ALLOW_ROW_LOCKS = ON,
            ALLOW_PAGE_LOCKS = ON,
            FILLFACTOR = 90
        ) ON FG_eFut,
    CONSTRAINT FK_JOGOS_X_LOCAIS_JOGOS FOREIGN KEY (ID_LOCAL) REFERENCES dbo.LOCAIS_JOGOS(ID_LOCAL)
) ON FG_eFut;


CREATE TABLE dbo.JOGADORES (
    ID_JOGADOR INT IDENTITY,
    STATUS_JOGADOR VARCHAR(50),
    FREQUENCIA INT,
    NOME VARCHAR(100) NOT NULL,
    APELIDO VARCHAR(50),
    WHATS VARCHAR(20) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
	CONSTRAINT PK_JOGADORES PRIMARY KEY CLUSTERED (ID_JOGADOR ASC)
			WITH (
        PAD_INDEX = OFF,
        STATISTICS_NORECOMPUTE = OFF,
        IGNORE_DUP_KEY = OFF,
        ALLOW_ROW_LOCKS = ON,
        ALLOW_PAGE_LOCKS = ON,
        FILLFACTOR = 90
    ) ON FG_eFut
) ON FG_eFut;

ALTER TABLE dbo.JOGADORES
ADD user_adm BIT NULL;

ALTER TABLE dbo.JOGADORES
ADD CONSTRAINT UQ_WHATS UNIQUE (WHATS);


CREATE TABLE dbo.LISTA_JOGOS (
	ID_LISTA_JOGO INT IDENTITY,
    ID_JOGO INT NOT NULL,
    ID_JOGADOR INT NOT NULL,
	POSICAO_LISTA INT NOT NULL,
	DATA_HORA_REGISTRO DATETIME NOT NULL  DEFAULT GETDATE(),
    TIPO_JOGADOR VARCHAR(10),
	CONSTRAINT PK_LISTA_JOGOS PRIMARY KEY CLUSTERED (ID_LISTA_JOGO ASC),
    CONSTRAINT FK_LISTA_JOGOS_X_JOGOS FOREIGN KEY (ID_JOGO) REFERENCES dbo.JOGOS(ID_JOGO),
	CONSTRAINT FK_LISTA_JOGOS_X_JOGADORES FOREIGN KEY (ID_JOGADOR) REFERENCES dbo.JOGADORES(ID_JOGADOR),
	CONSTRAINT CK_LISTA_JOGOS_TIPO_JOGADOR CHECK (TIPO_JOGADOR IN ('GOLEIRO', 'LINHA', 'SUPLENTE'))
)ON FG_eFut;

CREATE TABLE dbo.REGISTROS_JOGADORES (
	ID_REGISTRO_JOGADOR INT IDENTITY,
	ID_JOGO INT NOT NULL,
    ID_JOGADOR INT,
	POSICAO_LISTA INT NOT NULL,
    ACAO VARCHAR(50) NOT NULL,
	DATA_HORA_REGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
	TIPO_JOGADOR VARCHAR(10),
    CONSTRAINT PK_REGISTROS_JOGADORES PRIMARY KEY CLUSTERED (ID_REGISTRO_JOGADOR ASC),
	CONSTRAINT FK_REGISTROS_JOGADORES_X_JOGADORES FOREIGN KEY (ID_JOGADOR) REFERENCES dbo.JOGADORES(ID_JOGADOR),
	CONSTRAINT CK_REGISTROS_JOGADORES_ACAO CHECK (ACAO IN('INSERIDO', 'RETIRADO'))
)ON FG_eFut;

CREATE TABLE dbo.PREMIACOES (
    ID_PREMIACAO INT IDENTITY,
    STATUS_PREMIACAO VARCHAR(50),
    VENCEDOR INT NULL REFERENCES dbo.JOGADORES(ID_JOGADOR),
    DESCRICAO_REGRA VARCHAR(200)
	CONSTRAINT PK_PREMIACOES PRIMARY KEY CLUSTERED (ID_PREMIACAO ASC),
	CONSTRAINT CK_PREMIACOES_STATUS_PREMIACAO CHECK (STATUS_PREMIACAO IN('ABERTA' , 'REALIZADA'))
);

CREATE TABLE dbo.FINANCEIRO_JOGOS (
    ID_LANCAMENTO INT IDENTITY ,
    TIPO VARCHAR(10), 
    DESCRICAO VARCHAR(200),
    VALOR MONEY,
    DESCONTO_ACRESCIMO MONEY,
    VALOR_FINAL AS (VALOR + DESCONTO_ACRESCIMO) PERSISTED,
	CONSTRAINT PK_FINANCEIRO_JOGOS PRIMARY KEY CLUSTERED (ID_LANCAMENTO ASC),
	CONSTRAINT CK_FINANCEIRO_JOGOS_TIPO CHECK (TIPO IN('ENTRADA' , 'SAIDA'))
)ON FG_eFut;

CREATE TABLE dbo.EVENTO (
    ID_EVENTO INT IDENTITY,
    TIPO_EVENTO VARCHAR(50), -- EXEMPLOS: 'CHURRASCO', 'ACAO SOCIAL', 'FUT BONUS'
    DATA DATE NOT NULL,
    DESCRICAO VARCHAR(200),
    LOCAL VARCHAR(100),
    VALOR MONEY,
	CONSTRAINT PK_EVENTO PRIMARY KEY CLUSTERED (ID_EVENTO ASC)
)ON FG_eFut;

CREATE TABLE dbo.REGRAS_JOGOS (
    ID_REGRA INT IDENTITY,
    STATUS_REGRA VARCHAR(50),
    TIPO VARCHAR(50), -- 'GERAL' OU 'INDIVIDUAL'
    DESCRICAO VARCHAR(200),
	CONSTRAINT PK_REGRAS_JOGOS PRIMARY KEY CLUSTERED (ID_REGRA ASC),
	CONSTRAINT CK_REGRAS_JOGOS_STATUS_REGRA CHECK(STATUS_REGRA IN ('ATIVA','INATIVA'))  
)ON FG_eFut;

CREATE TABLE dbo.REGRAS_APP (
    ID_REGRA INT IDENTITY,
    DESCRICAO VARCHAR(100),
    VALOR_REGRA VARCHAR(100),
	CONSTRAINT PK_REGRAS_APP PRIMARY KEY CLUSTERED (ID_REGRA ASC)
)ON FG_eFut;

CREATE TABLE dbo.TAMPINHAS (
    ID_TAMPINHA INT IDENTITY ,
    COR VARCHAR(20),
    ID_JOGO INT,
    DATA_HORA_GERAR DATETIME,
    DATA_HORA_SORTEIO DATETIME,
    ID_JOGADOR INT,
    GOLEIRO_ENTRA BIT
	CONSTRAINT PK_TAMPINHAS PRIMARY KEY CLUSTERED (ID_TAMPINHA ASC),
	CONSTRAINT FK_TAMPINHAS_X_JOGOS FOREIGN KEY (ID_JOGO) REFERENCES  dbo.JOGOS(ID_JOGO),
	CONSTRAINT FK_TAMPINHAS_X_JOGADORES FOREIGN KEY (ID_JOGADOR) REFERENCES  dbo.JOGADORES(ID_JOGADOR)
)ON FG_eFut;

INSERT INTO dbo.regras_app (descricao, valor_regra)
VALUES 
    ('Admin do app', NULL),
    ('Organizador 1', NULL),
    ('Organizador 2', NULL),
    ('Organizador 3', NULL),
    ('Controla Frequencia', 'S'),
    ('Utiliza sorteio de tampinhas', 'S'),
    ('Goleiro fixo', 'S'),
    ('Jogadores_por_time', '5'),
    ('Goleiro entra no sorteio de tampinhas', 'N'),
    ('Cores de coletes', 'Vermelha;Verde;Azul;Amarela;Rosa'),
    ('Vagas linhas', '16'),
    ('Vagas goleiros', '3'),
    ('Vagas suplentes', '4');

/*========================================================| MODULO SISTEMA DE ORGANIZAÇÃO DE FUT - FIM |========================================================*/


use master;
