/*Cria tabelas e triggers de auditorias*/
use master;



use efut;


EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='EVENTO'
EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='FINANCEIRO_JOGOS'
EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='JOGADORES'
EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='JOGOS'
EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='LISTA_JOGOS'
EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='LOCAIS_JOGOS'
EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='PREMIACOES'
EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='REGISTROS_JOGADORES'
EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='REGRAS_APP'
EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='REGRAS_JOGOS'
EXEC DBO.[AUDITORIA_CRIA_TABELAS_E_TRIGGERS] @TABELA='TAMPINHAS'



use master;